# Generated by Django 4.2.2 on 2023-07-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='img',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
